###
GET http://localhost:3000/

###
GET http://localhost:3000/post

###
GET http://localhost:3000/post?id=12345

###
GET http://localhost:3000/post/123

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "id": "12345678",
    "name": "John",
    "message": "hello world"
}

###
PUT http://localhost:3000/post/12345678
Content-Type: application/json

{
    "id": "12345678",
    "name": "Itay",
    "message": "hello world!!!"
}

###
DELETE http://localhost:3000/post/12345

###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments?owner=Itay

###
GET http://localhost:3000/comments?owner=NOTItay

###
GET http://localhost:3000/comments?postId=12345

###
GET http://localhost:3000/comments?postId=12345&owner=Itay

###
GET http://localhost:3000/comments?postId=12345&owner=NOTItay

###
GET http://localhost:3000/comments?postId=123456789&owner=Itay

###
GET http://localhost:3000/comments/123

###
GET http://localhost:3000/comments/67828e370ba9ad74f6700bea

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "message": "hello world!!!",
    "owner": "Itay",
    "postId": "12345"
}

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "_id": "6782920ce39804cd14c2dfb0",
    "message": "comment to delete",
    "owner": "delete",
    "postId": "9999999"
}

###
PUT http://localhost:3000/comments/12345678
Content-Type: application/json

{
    "message": "UPDATED!!!",
    "owner": "test",
    "postId": "12345678"
}

###
DELETE http://localhost:3000/comments/12345

###
DELETE http://localhost:3000/comments/6782920ce39804cd14c2dfb0